# Generated by Django 4.2.15 on 2024-11-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_race',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
