# Generated by Django 4.2.15 on 2024-11-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0004_alter_character_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
