# Generated by Django 4.2.15 on 2024-11-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheet', '0005_alter_character_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, default='images/placeholder_profile.svg', null=True, upload_to='character_images/'),
        ),
    ]
